apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.3
    helm:
      values: |
        provider: aws
        aws:
          zoneType: public
          region: eu-west-1
        txtOwnerId: external-dns
        policy: upsert-only
        sources:
          - service
          - ingress
        domainFilters: [geekops.dev]
        logLevel: debug
        interval: 1m
        triggerLoopOnEvent: false
        registry: txt
        txtPrefix: external-dns-
        
        # Enhanced RBAC for kubeadm clusters
        rbac:
          create: true
          additionalPermissions:
            - apiGroups: [""]
              resources: ["nodes"]
              verbs: ["list","watch"]
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get","list","watch"]
        
        serviceAccount:
          create: true
          # Uncomment if using IAM roles for service accounts (IRSA)
          # annotations:
          #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/external-dns
        
        # Add tolerations for control plane nodes if needed
        tolerations: []
        
        # Resource limits to prevent OOM kills
        resources:
          limits:
            memory: 256Mi
            cpu: 250m
          requests:
            memory: 128Mi
            cpu: 100m
        
        # Set AWS region
        env:
          - name: AWS_DEFAULT_REGION
            value: "eu-west-1"
        
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m